### ISSUE TITLE
How to simulate PV module only?

### ISSUE THREAD

**Issue by ardiantovn** [ALSETLab/MicroGrid#3]
I am trying to simulate only a PV module. The simulation is run with the configuration as shown below. I want to get Power (W) vs Voltage (V) and Current (A) vs Voltage (V).  However, I get an error. How to do the PV module simulation correctly?
thank you

![test1](https://user-images.githubusercontent.com/16162415/70406800-79c98580-1a74-11ea-8f9e-623916dbbb31.PNG)
![test2](https://user-images.githubusercontent.com/16162415/70406802-79c98580-1a74-11ea-8659-ce2c00d48f27.PNG)

**Comment by marcelofcastro** [comment]
Hi @nugrohoav,  

A way of simulating only the PV module is to put the PV in supplying power to a resistor. Just like the figure below. I simulated it in Dymola, but I think it should work fine in OpenModelica. Let me know how it goes.

![pv_simple](https://user-images.githubusercontent.com/17451510/70447683-24d64100-1a6d-11ea-8c1a-4303059cbe1c.png)

**Comment by marcelofcastro** [comment]
@nugrohoav By the way, don't forget the ground node. It is important to set a voltage reference to your circuit.

**Comment by nugrohoav** [comment]
Thanks for the explanation. I am also learning to plot simulation results. I have managed to plot Voltage VS Current via Parametric Plot. However, I also want to plot Power VS Voltage. How to do it?
Thank you

**Comment by marcelofcastro** [comment]
@nugrohoav Did it my example work?

To plot power, you should try to plot a mathematical expression. I do not know if this is possible in OpenModelica. 

Another way to do it is to put a CurrentSensor in series with the resistor and a VoltageSensor in parallel with the resistor. The output of both sensors need to be converted to Real by using the Sensor2Real interface. The output could be then multiplied in a simple Modelica.Blocks.Math.Product block and you would get the power as the output.

**Comment by nugrohoav** [comment]
Yes, your example is work, thank you. I'm trying your idea. Where is the Sensor2Real Interface?

**Comment by marcelofcastro** [comment]
The interface is in Sensors.Interfaces.Sensor2Real

**Comment by nugrohoav** [comment]
Could you help me, how to resolve this error?

![pv](https://user-images.githubusercontent.com/16162415/70453541-87febc80-1adb-11ea-950b-f50358239285.PNG)

**Comment by nugrohoav** [comment]
Thank you for your idea. I can already do the plot. Thank you very much...

**Comment by nugrohoav** [comment]
Hello, I want to ask about the simulation. 
![set](https://user-images.githubusercontent.com/16162415/70558823-3aa44d00-1bb8-11ea-8c00-0969cf7c706c.PNG)

I did a simulation with a configuration like the picture above.

I expect the simulation results as shown below.
![plot](https://user-images.githubusercontent.com/16162415/70559113-b0101d80-1bb8-11ea-90b3-0466bd7f277e.PNG)


However, I get results like the image below.
![res](https://user-images.githubusercontent.com/16162415/70559174-c74f0b00-1bb8-11ea-8e5f-a2ab331e233e.PNG)


What things need to be arranged to get the results I want?

Thank you

**Comment by marcelofcastro** [comment]
Hi @nugrohoav 

for this case, instead of connecting it to a resistor, you'd need to connect the PV to a variable DC voltage source. By varying the DC voltage from 0 to 35 volts you'd get the result that you want. Right now I don't have a model of a variable DC voltage source in my library but you can use it from the Modelica Standard Library. 

I designed an experiment and the result is the following:
![Result](https://user-images.githubusercontent.com/17451510/70646826-b7b1df80-1c15-11ea-802d-a1085cd8e10f.png)


I will send you the file so you can modify it

**Comment by Jes-f** [comment]
Hello ,
I am new to using OpenModelica, I am trying to simulate their MicroGrid package, but it won't compile.
Can you help me identify the error?.
Thank you.

![image](https://user-images.githubusercontent.com/69703953/90303695-6df55500-de86-11ea-9d4b-2e9d10b9494e.png)
![image](https://user-images.githubusercontent.com/69703953/90303700-87969c80-de86-11ea-9661-5c5c23cd6097.png)
![image](https://user-images.githubusercontent.com/69703953/90303703-92e9c800-de86-11ea-8618-c766cd105817.png)

**Comment by marcelofcastro** [comment]
> Hello ,
> I am new to using OpenModelica, I am trying to simulate their MicroGrid package, but it won't compile.
> Can you help me identify the error?.
> Thank you.
> 
> ![image](https://user-images.githubusercontent.com/69703953/90303695-6df55500-de86-11ea-9d4b-2e9d10b9494e.png)
> ![image](https://user-images.githubusercontent.com/69703953/90303700-87969c80-de86-11ea-9661-5c5c23cd6097.png)
> ![image](https://user-images.githubusercontent.com/69703953/90303703-92e9c800-de86-11ea-8618-c766cd105817.png)

Hi! Indeed the library was originally developed to work on SystemModeler and Dymola so, the problem might be that a component might not be working well in OpenModelica. I will try to check this in the next weeks and I will reach you out if I have a solution for this problem.

**Comment by marcelofcastro** [comment]
> Hello ,
> I am new to using OpenModelica, I am trying to simulate their MicroGrid package, but it won't compile.
> Can you help me identify the error?.
> Thank you.
> 
> ![image](https://user-images.githubusercontent.com/69703953/90303695-6df55500-de86-11ea-9d4b-2e9d10b9494e.png)
> ![image](https://user-images.githubusercontent.com/69703953/90303700-87969c80-de86-11ea-9661-5c5c23cd6097.png)
> ![image](https://user-images.githubusercontent.com/69703953/90303703-92e9c800-de86-11ea-8618-c766cd105817.png)

By the way, from the picture you sent it looks like the models are not there in the library. So the problem might be that the components are not correctly identified.

**Comment by Jes-f** [comment]
Hi, I did your example again (PV example), but I had to make some
modifications to your data to make it work on the DC / DC converter, and I
also got some alerts.
change the frequency of the inverter (photo _ yellow color)
Could you help me mitigate the alerts?
[image: image.png]
[image: image.png]
[image: image.png]



I'm trying to integrate a synchronous generator to your network but I can't
think of how.

regards.

[image: image.png]

Em qui., 20 de ago. de 2020 às 11:54, Marcelo de C. Fernandes <
notifications@github.com> escreveu:
